"""dbkit error model (§13). Import everything from ``dbkit.errors``."""

from __future__ import annotations

from .base import (
    DatabaseCancellationError,
    DatabaseCheckViolationError,
    DatabaseCircuitOpenError,
    DatabaseCommitUnknownError,
    DatabaseConfigurationError,
    DatabaseConnectionError,
    DatabaseDeadlockError,
    DatabaseError,
    DatabaseForeignKeyViolationError,
    DatabaseIntegrityError,
    DatabaseLockTimeoutError,
    DatabaseMappingError,
    DatabaseNotNullViolationError,
    DatabaseOverloadedError,
    DatabasePermissionError,
    DatabasePoolTimeoutError,
    DatabaseProgrammingError,
    DatabaseQueryTimeoutError,
    DatabaseReadOnlyError,
    DatabaseResultError,
    DatabaseRoutingError,
    DatabaseSerializationError,
    DatabaseSyntaxError,
    DatabaseTransactionError,
    DatabaseUnavailableError,
    DatabaseUniqueViolationError,
    DatabaseUnsupportedOperationError,
    ErrorCategory,
)
from .classifier import classify
from .redaction import redact_dsn, redact_params, sanitize_message
from .sqlstate import error_class_for_sqlstate

__all__ = [
    "DatabaseCancellationError",
    "DatabaseCheckViolationError",
    "DatabaseCircuitOpenError",
    "DatabaseCommitUnknownError",
    "DatabaseConfigurationError",
    "DatabaseConnectionError",
    "DatabaseDeadlockError",
    "DatabaseError",
    "DatabaseForeignKeyViolationError",
    "DatabaseIntegrityError",
    "DatabaseLockTimeoutError",
    "DatabaseMappingError",
    "DatabaseNotNullViolationError",
    "DatabaseOverloadedError",
    "DatabasePermissionError",
    "DatabasePoolTimeoutError",
    "DatabaseProgrammingError",
    "DatabaseQueryTimeoutError",
    "DatabaseReadOnlyError",
    "DatabaseResultError",
    "DatabaseRoutingError",
    "DatabaseSerializationError",
    "DatabaseSyntaxError",
    "DatabaseTransactionError",
    "DatabaseUnavailableError",
    "DatabaseUniqueViolationError",
    "DatabaseUnsupportedOperationError",
    "ErrorCategory",
    "classify",
    "error_class_for_sqlstate",
    "redact_dsn",
    "redact_params",
    "sanitize_message",
]
